refactor: cleaning code
SigwoTechnologies/metis-web pull request #66
Opened 2022-09-07 00:02 UTC by AlefrankM

2022-09-07 15:34 UTC, mmiranda-stackit requested changes
Please avoid using inline eslint rules disablers, please read my comments

2022-09-07 15:34 UTC, mmiranda-stackit commented on src/common/components/ui/Notification/index.tsx
> +        // eslint-disable-next-line security/detect-object-injection
Please avoid using inline eslint rules, it is better to use global rules, and if there is an exception, we should refactor whenever possible, or, as a last resource, create a new global rule disabling the entire rule.

2022-09-07 15:34 UTC, mmiranda-stackit commented on src/features/auth/services/interfaces/auth-service.interface.ts
> +    // eslint-disable-next-line @typescript-eslint/no-explicit-any
I think that we can type this response

2022-09-07 15:34 UTC, mmiranda-stackit commented on src/features/auth/services/metamask.service.ts
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
It is worth to investigate if there is a type definition for ethereum object, so we don't use any type.

2022-09-07 17:05 UTC, AlefrankM commented
This changes were to resolve some conflicts. Now I'm gonna refactor it

2022-09-07 18:23 UTC, AlefrankM commented on src/features/auth/services/interfaces/auth-service.interface.ts
> +    // eslint-disable-next-line @typescript-eslint/no-explicit-any
I'm searching

2022-09-09 00:43 UTC, mmiranda-stackit submitted a review, later dismissed
Looks good

2022-09-09 14:05 UTC, mmiranda-stackit approved these changes

2022-09-09 14:05 UTC, merged